# Copyright 2026 Kryton contributors
# SPDX-License-Identifier: Apache-2.0
version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps(go)"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps(docker)"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps(ci)"
